### PR TITLE
CORTX-31340:set  motr addb enabled = true in rgw config file

### PR DESCRIPTION
**Pull request by sachitanands**
Signed-off-by: Sachitanand Shelake <sachitanand.shelake@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Review by rohit-k-dwivedi — APPROVED** [review]

**Comment by sachitanands** [comment]
Triggered docker image job: 
https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6520/

**Comment by sachitanands** [comment]
Tested this changes with latest main branch,
docker Image,
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-6520-custom-ci 
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6520-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6520-custom-ci
(https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6520/console) 

deployment job : https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/6170 (Successful)
image

**Comment by sachitanands** [comment]
image

**Review by shriya-deshmukh — APPROVED** [review]

**Review by rahul-tripathi-git — APPROVED** [review]

**Review by cdeshmukh — APPROVED** [review]

**Comment by cdeshmukh** [comment]
@sachitanands have you tested the deployment with addb plugin build enabled? If not, we should.

**Comment by sachitanands** [comment]
> @sachitanands have you tested the deployment with addb plugin build enabled? If not, we should.

I missed this testing. I will test it quickly.
I have triggered new ci build with enabling that addb build option.
https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6538/console

**Comment by sachitanands** [comment]
Testing changes with below jobs
custom-ci job : https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6561 (In-progress)

**Pull request merged**
