### PR TITLE
change rgw concurrent request parameter

### PR DESCRIPTION
**Pull request by sjain09**
Signed-off-by: saurabh jain <saurabh.jain2@seagate.com>

# Problem Statement
The current default value of rgw_concurrent_max_requests is set very high compared to default thread pool size.
```
rgw_concurrent_max_requests = 1024
rgw_thread_pool = 10
```
Given the limited resource availability in the VM environment and the size of threadpool in rgw server we should keep rgw_concurrent_max_requests to equal to rgw thread pool size.

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [x] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by cdeshmukh** [comment]
> Given the limited resource availability in the VM environment and the size of threadpool in rgw server we should keep rgw_concurrent_max_requests to equal to rgw thread pool size.

Didnt we decided to keep rgw_concurrent_max_requests double the size of rgw_thread_pool size, to allow some requests to get accumulated in request queues(if any such exists)

**Comment by cdeshmukh** [comment]
Also branch needs rebase

**Review by sachitanands — APPROVED** [review]

**Comment by sjain09** [comment]
> > Given the limited resource availability in the VM environment and the size of threadpool in rgw server we should keep rgw_concurrent_max_requests to equal to rgw thread pool size.
> 
> Didnt we decided to keep rgw_concurrent_max_requests double the size of rgw_thread_pool size, to allow some requests to get accumulated in request queues(if any such exists)

Since we are have only two CPUs to work with, I would recommend to keep rgw_concurrent_max_requests equal to the thread pool size. 
Making  rgw_concurrent_max_requests double the size of threadpool also requires number of CPUs half of the of theadpool size. Which we don't have in k8 environment as resource limits are in place.

**Comment by sjain09** [comment]
> Also branch needs rebase

Done

**Review by cdeshmukh — APPROVED** [review]

**Pull request merged**
