### PR TITLE
CORTX-32793: update rgw resource limit formula

### PR DESCRIPTION
**Pull request by sjain09**
After fixing defect CORTX-34142, update needs to be made for rgw resource limit related parameters in-order fine tune the formula.

Signed-off-by: Saurabh Jain <saurabh.jain2@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Review by sachitanands — APPROVED** [review]
looks good

**Review by priyanka25081999 — APPROVED** [review]

**Comment by sjain09** [comment]
retest this please

**Review by cdeshmukh — APPROVED** [review]

**Comment by cdeshmukh** [comment]
@sjain09 please check why 1N deployment failing, meantime i will retrigger
https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/rgw-integration/159/

**Comment by cdeshmukh** [comment]
retest this please

**Review by shriya-deshmukh — APPROVED** [review]

**Pull request merged**
